### ISSUE TITLE
interfacing with topic-modeling-tool through command line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#11]
```
Hello,
How can I train and obtain results as the GUI using command line and saving the 
results with the original file name. Thanks
```

Original issue reported on code.google.com by `greatale...@gmail.com` on 16 Mar 2015 at 9:39

**Comment by senderle** [comment]
For command-line functionality, use the underlying library that the TMT is built on: [MALLET](http://mallet.cs.umass.edu/).
