### ISSUE TITLE
Contact original creators about relicensing from the EPL

### ISSUE THREAD

**Issue by senderle** [senderle/topic-modeling-tool#50]
I think it would be best to relicense this tool under the MIT license. I don't see the point in copylefting a pure front-end like this, and a permissive license might draw other developers to the project. But unless the creators are willing to relicense it, we're stuck with this weird, non-standard Eclipse license.

**Comment by arunbg** [comment]
Hey @senderle pleasantly surprised to see a fork of the topic model tool here :)
I've changed the license to Apache 2.0. At the time, this was what Mallet was licensed under. But looks like they have been Apache 2.0 for a while now. Hope this helps.

**Comment by senderle** [comment]
Thank you @arunbg! I am sorry for the slow reply — this arrived at a hectic moment and then I totally forgot. It sounds like the Apache 2.0 license is pretty similar to MIT — I'll look into the details and relicense when I can. Thanks for creating this tool — I know a lot of people who have found it helpful!
