### ISSUE TITLE
Exception error when running topic model on folder containing subfolders

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#6]
```
What steps will reproduce the problem?
1. Running "Learn Topics" on a file folder that contains multiple folders, each 
with its own multiple folders (basically trying to look at data two folders 
beneath the overall folder)
2.
3.

What is the expected output? What do you see instead?
When I run it on a single folder within the main folder, I get actual results. 
When I try to run it on the main folder that contains the subfolders and their 
corresponding subfolders, I get the exception errors that others have gotten 
(I'm not posting them here because they read basically the same as the others 
who have posted).

An explanation - I am using the Enron email database that was generated and 
made publicly available after the Enron scandal. Within the overall "maildir" 
folder are folders for 150 users, each of those users having multiple folders 
within their emails (inbox, sent, etc.). Running the program on the folder of a 
single user (e.g., lay-k for Ken Lay's username) produces results. Running it 
using "maildir" as the input file produces the error. I would like to generate 
a list of topics based on the overall database without having to flatten the 
existing folder structure.

What version of the product are you using? On what operating system?
I can't tell what version it is - I just downloaded it from this site a couple 
of days ago. I am running Windows 7.

Please provide any additional information below.


```

Original issue reported on code.google.com by `dgoodson...@gmail.com` on 6 May 2013 at 4:39

**Comment by senderle** [comment]
"I would like to generate a list of topics based on the overall database without having to flatten the existing folder structure." A noble goal! I would also like that. It might not be entirely trivial to implement in Java. (This is where I admit, perversely, that although this is a Java project and I am in the process of committing myself to maintaining it, I don't know Java all that well yet.) 

For that reason, I won't be addressing this soon, in all likelihood. It would be a nice feature though.

**Comment by senderle** [comment]
After more thought, I've realized this will be quite difficult to do, since this is a restriction imposed by MALLET. Although I could write something to flatten the hierarchy in advance, that's not really the same thing, and it complicates other, simpler use cases. I'm afraid this is just outside the scope of the tool. Closing, won't fix (unless somebody can change my mind.)
