### ISSUE TITLE
Stable Release 1.0.0 Fails to Install

### ISSUE THREAD

**Issue by zhanwenchen** [senderle/topic-modeling-tool#63]
Clicking on "TopicModelingTool.dmg"
<img width="375" alt="screen shot 2017-08-21 at 12 05 29 pm" src="https://user-images.githubusercontent.com/5029736/29528363-cfb069e2-8669-11e7-80f6-ea00374c3d10.png">

Clicking on "TopicModelingTool.jar"
<img width="423" alt="screen shot 2017-08-21 at 12 05 59 pm" src="https://user-images.githubusercontent.com/5029736/29528364-d16b3dc0-8669-11e7-9efb-6f198fd85b80.png">

Running `chmod 777 ./*` didn't help. I did build from source which worked fine.

OS: macOS Sierra 10.12.6

**Comment by senderle** [comment]
I'm afraid I couldn't replicate this. I have the same version of Mac OS and was able to download and open the DMG without any trouble. 

How did you download it? Github doesn't always handle file downloads in the expected way. When I checked, this was the exact url I used.

https://github.com/senderle/topic-modeling-tool/raw/master/TopicModelingTool.dmg

Try that and see what happens.

**Comment by zhanwenchen** [comment]
I used [](https://github.com/senderle/topic-modeling-tool/releases) to download the source code zip.

And yes, the link you provided works.

**Comment by senderle** [comment]
This doesn't seem like it can be closed yet, because I don't know what the problem was. Please comment if you've had the same problem.

**Comment by hawc2** [comment]
I didn't have this problem, but a friend did. The only thing that worked: if you download the dmg file directly, it doesn't get the same error. Not sure if that means there's an error with the zip file or what

**Comment by senderle** [comment]
@hawc2 thanks. Revisiting this, I wonder if it has something to do with github's Large File Storage setup. The zip file might not contain the actual .dmg file -- it might just contain a pointer to the file. When you clone the repo through git, it knows to download the file itself, but when you download the zip file, you just get the pointer...

**Comment by senderle** [comment]
Aha, yes, that seems like it must be the problem. See this issue under the LFS plugin.

https://github.com/git-lfs/git-lfs/issues/1648

**Comment by senderle** [comment]
This is unavoidable behavior caused by git's Large File Storage plugin. See the issue here:

git-lfs/git-lfs#1648

The only solution is to avoid downloading the repository as a zip file. If you wish to install a pre-built binary, you'll need to directly download the binary file itself, or clone the repository using git, with the git-lfs plugin installed.
