### ISSUE TITLE
Divide Input option is skipping files

### ISSUE THREAD

**Issue by senderle** [senderle/topic-modeling-tool#67]
As reported in #65. @shawngraham writes:

>I went and tried it again, armed with my new knowledge of how it works. In the results, when I opened the metadata.csv, a number of my documents were no longer present; that is to say, no results recorded for them. I had n set for 1000, so I thought perhaps the missing ones were smaller and somehow got folded into the previous 1000-chunk, but no, the missing ones should have been split into three or four chunks at least. So I'm not sure what's going on there... I can't seem to see the commonality between the documents that get dropped.

**Comment by senderle** [comment]
@shawngraham, it also occurs to me that odd characters in filenames can sometimes cause problematic behavior. If possible, could you upload just the `topic-metadata.csv` file here?

**Comment by shawngraham** [comment]
Hi, I'm sorry - this fell off the radar because I got swamped with other things. I'll try to return to it later this month once the smoke settles!

**Comment by senderle** [comment]
No problem! And thanks!

**Comment by senderle** [comment]
Unfortunately I think I have to close this as unable-to-reproduce. Will reopen if it comes up again.
