### ISSUE TITLE
--random-seed

### ISSUE THREAD

**Issue by scottkleinman** [senderle/topic-modeling-tool#68]
Not a lot of people know about MALLET's `--random-seed` option. Would this be something simple to add?

**Comment by scottkleinman** [comment]
Thanks!

Keeping the UI from getting too forbidding is definitely a challenge. Off the top of my head, I'd suggest one possibility would be to add split `Optional settings...`. Into `Settings` and `Advanced` buttons, or something like that. You could move tokenisation, segmentation, and threading functions (as well as `random-seed`) to the advanced section. That, of course, is just my intuition of what is "advanced", but some user feedback would confirm what the majority users find most intuitive.

**Comment by senderle** [comment]
It's certainly *possible*, and Claude you're convincing me that I should just do it. For now I'll just add it to the optional settings menu alongside a couple of other arcane settings that I've needed to use.

**Comment by senderle** [comment]
Done! Alas the native windows build is not yet complete, but the Mac build and basic `jar` file are both up-to-date with this change.
