### ISSUE TITLE
Is it possible to get sampling convergence measure

### ISSUE THREAD

**Issue by findgit123** [senderle/topic-modeling-tool#75]
@senderle 

We are testing your tool. Is it possible to get sampling convergence measure? How to get that? And how to explain that measure? 

Thanks

**Comment by senderle** [comment]
Apologies for the slow reply — I missed the notification for this issue. Right now the best indication of convergence I know of is the log likelihood per token (LL/token) measurement, which should slowly become less negative over time as the model converges. Once that value stops changing significantly, the model has converged. There are probably better measures, but I am not up on recent theory, so I am not sure what they are or how to incorporate them into the tool. Let me know if you have ideas!

**Comment by senderle** [comment]
Closing this for now. I still know of no better convergence measure than the LL/token value.
